name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        compiler: [g++-10, g++11, clang++-10, clang++-11]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure CMake
      env:
        CXX: ${{ matrix.compiler }}
      run: cmake -B ${{github.workspace}}/build

    - name: Build with CMake
      run: cmake --build ${{github.workspace}}/build

    - name: Test with CMake/CTest
      run: |
        ctest --build-and-test . build --build-generator "Unix Makefiles"  --build-noclean --rerun-failed --output-on-failure